Разметка всех страниц
htmlacademy-htmlcss/2428785-gllacy-1 pull request #2
Opened 2023-10-01 08:42 UTC by posplawone

2023-10-01 10:44 UTC, DoberBober commented on index.html
> +        <button class="navigation-button" type="arrow"></button>
Кнопка не нужна, удали её.

2023-10-01 10:45 UTC, DoberBober commented on index.html
> +        <a class="navigation-link" href="delivery.html">Доставка и оплата</a>
У ссылок, которые никуда не ведут, поставь заглушки `href="#"`.

2023-10-01 10:46 UTC, DoberBober commented on index.html
> +        <button class="button button-buy" href="#">Заказать</button>
Ссылка.

2023-10-01 10:47 UTC, DoberBober commented on index.html
> +          <button class="button-banner-buy" type="button">Хочу подарок</button>
Тоже ссылки.

2023-10-01 10:48 UTC, DoberBober commented on index.html
> +    <selection class="tatse">
```suggestion
    <section class="tatse">
```

2023-10-01 10:49 UTC, DoberBober commented on index.html
> +          <button class="taste-item-button" type="button">
Ссылка.

2023-10-01 10:50 UTC, DoberBober commented on index.html
> +        <selection class="about">
Тут и далее тоже `selection`, вместо `section` написано.

2023-10-01 10:51 UTC, DoberBober commented on index.html
> +          <ul class="advertisement-list">
Этот два секшна, а не пункта списка, скорее.

2023-10-01 10:51 UTC, DoberBober commented on index.html
> +                <form class="news" action="#" method="post">
```suggestion
                <form class="news" action="https://echo.htmlacademy.ru" method="post">
```

2023-10-01 10:52 UTC, DoberBober commented on index.html
> +          <form class="delivery-form" action="#" method="post">
```suggestion
          <form class="delivery-form" action="https://echo.htmlacademt.ru" method="post">
```

2023-10-01 10:53 UTC, DoberBober commented on index.html
> +              <input type="text" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
```suggestion
              <input type="tel" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
```

2023-10-01 10:54 UTC, DoberBober commented on index.html
> +            <button class="office-button" type="button">Форма обратной связи</button>
Ссылка.

2023-10-01 10:55 UTC, DoberBober commented on index.html
> +    <a class="developer" href="#">
Поставь ссылку на Академию.

2023-10-01 10:55 UTC, DoberBober requested changes
В целом - хорошо. Есть небольшие правки. Ну и вторую страницу надо сделать.

2023-10-03 04:27 UTC, posplawone commented on index.html
> +        <button class="navigation-button" type="arrow"></button>
Удалил

2023-10-03 04:27 UTC, posplawone commented on index.html
> +        <a class="navigation-link" href="delivery.html">Доставка и оплата</a>
Поставил заглушки

2023-10-03 04:27 UTC, posplawone commented on index.html
> +    <selection class="tatse">
Исправил

2023-10-03 04:30 UTC, posplawone commented on index.html
> +        <selection class="about">
Исправил

2023-10-03 04:40 UTC, posplawone commented on index.html
> +          <ul class="advertisement-list">
Надеюсь правильно понял, исправил

2023-10-03 04:41 UTC, posplawone commented on index.html
> +                <form class="news" action="#" method="post">
Исправил

2023-10-03 04:49 UTC, posplawone commented on index.html
> +              <input type="text" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
Исправил

2023-10-03 04:51 UTC, posplawone commented on index.html
> +    <a class="developer" href="#">
Поставил

2023-10-03 04:52 UTC, posplawone commented on index.html
> +        <button class="button button-buy" href="#">Заказать</button>
> Ссылка.

Не могу понять какую ссылку вставлять

2023-10-03 05:26 UTC, posplawone commented on index.html
> +          <button class="button-banner-buy" type="button">Хочу подарок</button>
Поставил заглушку, не знаю как ссылку вставлять

2023-10-03 05:26 UTC, posplawone commented on index.html
> +          <button class="taste-item-button" type="button">
Поставил заглушку, не знаю какую ссылку вставлять

2023-10-03 05:27 UTC, posplawone commented on index.html
> +          <form class="delivery-form" action="#" method="post">
Исправил

2023-10-03 05:27 UTC, posplawone commented on index.html
> +            <button class="office-button" type="button">Форма обратной связи</button>
Поставил заглушку, не знаю какую ссылку вставлять

2023-10-03 08:21 UTC, DoberBober commented on index.html
> +        <button class="button button-buy" href="#">Заказать</button>
Просто заглушка - `href="#"`.

2023-10-03 08:21 UTC, DoberBober commented on index.html
> +          <button class="button-banner-buy" type="button">Хочу подарок</button>
Тут тоже ссылки (в смысле тег `button` заменить на `a`, а в качестве `href` - решетка).

2023-10-03 08:24 UTC, DoberBober commented on catalog.html
> +          <button class="product-item-button" type="button" href="#">
Тоже ссылка.)

2023-10-03 08:24 UTC, DoberBober commented on catalog.html
> +          <button class="button-show-more" type="button">Показать еще</button>
Тоже ссылка.

2023-10-03 08:26 UTC, DoberBober commented on catalog.html
> +          <h3 class="product-item-title">Малинка</h3>
Фотки товаров пропустил.
Фотку обернуть в ссылку, внутри h3 тоже вставить ссылку (по клику может перекидывать на карточку мороженного).

2023-10-03 08:26 UTC, DoberBober requested changes
Кнопки на ссылки поменять и всё.

2023-10-03 10:11 UTC, merged